#!/bin/bash

# kf2-srv is a command line tool for managing a set of Killing Floor 2 servers.
# Copyright (C) 2019-2021 GenZmeY
# mailto: genzmey@gmail.com
# 
# This file is part of kf2-srv.
#
# kf2-srv is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

cmd_need_superuser        () { false ;}
cmd_need_steamuser        () { true  ;}
cmd_need_installed_server () { false ;}

function cmd_usage ()
{
	echo "<workshop_id>..."
}

function cmd_info ()
{
	echo "Add specified resource(s) from steam workshop"
}

function cmd_help ()
{
	echo "workshop_id can be a resource ID or a link to a resource in workshop."
}

function cmd_main ()
{
	include "$LibDir/workshop.lib"
	
	workshop_add "$@"
}

