name: build release

on:
    push:
        tags:
        - '[0-9]+.[0-9]+.[0-9]+-[0-9]+'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - name: checkout
            uses: actions/checkout@v2

          - name: build
            uses: ./.github/workflows/docker
            id: build
            with:
              target: 'all'

          - name: create release
            id: create_release
            uses: actions/create-release@latest
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
                tag_name: ${{ github.ref }}
                release_name: Release ${{ github.ref }}
                draft: false
                prerelease: false
                
          - name: upload srpm
            uses: actions/upload-release-asset@v1
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
                upload_url: ${{ steps.create_release.outputs.upload_url }} 
                asset_path: /home/runner/work/kf2-srv/kf2-srv/SRPMS/${{ steps.build.outputs.srpm_name }}
                asset_name: ${{ steps.build.outputs.srpm_name }}
                asset_content_type: application/gzip
                
          - name: upload rpm
            uses: actions/upload-release-asset@v1
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
                upload_url: ${{ steps.create_release.outputs.upload_url }} 
                asset_path: /home/runner/work/kf2-srv/kf2-srv/RPMS/noarch/${{ steps.build.outputs.rpm_name }}
                asset_name: ${{ steps.build.outputs.rpm_name }}
                asset_content_type: application/gzip
                
