name: tests (master)

on:
    push:
        branches:
        - master

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: run tests
        uses: ./.github/workflows/docker
        with:
          target: 'test'

